jobs:
  build:
    name: Build Checker
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: setup-java
      name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      uses: burrunan/gradle-cache-action@v1.10
      with:
        arguments: clean assemble -PcheckerFramework=true
        remote-build-cache-proxy-enabled: false
name: Build Checker
on:
  repository_dispatch:
    types: trigger-ga___build-checker.yml
