jobs:
  build:
    name: Build Maven Examples Ubuntu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: setup-java
      name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      name: Build Examples
      run: mvn --batch-mode --update-snapshots clean package appassembler:assemble
        -e
      working-directory: ./examples
    - continue-on-error: true
      name: Build Spring Servlet example
      run: mvn --batch-mode --update-snapshots clean package appassembler:assemble
        -e
      working-directory: ./examples/spring/servlet
name: Build Maven Examples
on:
  repository_dispatch:
    types: trigger-ga___build-maven-examples.yml
