jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: setup-java
      name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: ./gradlew clean assemble check --stacktrace
    strategy:
      matrix:
        include:
        - coverage: true
          java: 8
          os: ubuntu-latest
        java:
        - 8
        os:
        - macos-latest
        - ubuntu-latest
name: Build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
