jobs:
  build:
    name: Build Gradle Examples Ubuntu
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - continue-on-error: true
      id: setup-java
      name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
    - continue-on-error: true
      uses: burrunan/gradle-cache-action@v1.10
      with:
        remote-build-cache-proxy-enabled: false
    - continue-on-error: true
      name: Build Examples
      run: ./gradlew clean assemble --stacktrace && ./gradlew check && ./gradlew verGJF
      working-directory: ./examples
    - continue-on-error: true
      name: Build Spring Servlet example
      run: ./gradlew clean assemble --stacktrace && ./gradlew check && ./gradlew verGJF
      working-directory: ./examples/spring/servlet
name: Build Gradle Examples
on:
  repository_dispatch:
    types: trigger-ga___build-gradle-examples.yml
